plugins {
    id 'application'
}

dependencies {
    implementation project(':core')
    implementation 'com.badlogicgames.gdx:gdx-backend-headless:1.14.2'
    runtimeOnly 'com.badlogicgames.gdx:gdx-platform:1.14.2:natives-desktop'
}

application {
    mainClass = 'com.example.matchreplay.server.ServerLauncher'
}
