apply plugin: "application"

application {
    mainClass = "com.myproject.headless.HeadlessLauncher"
}

dependencies {
    implementation project(":core")
    implementation "com.badlogicgames.gdx:gdx-backend-headless:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
}

run {
    standardInput = System.in
}
