plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

def gdxVersion = '1.14.2'

dependencies {
    implementation "com.badlogicgames.gdx:gdx:${gdxVersion}"
    implementation "com.badlogicgames.gdx:gdx-backend-headless:${gdxVersion}"
    implementation "com.badlogicgames.gdx:gdx-platform:${gdxVersion}:natives-desktop"
}

application {
    mainClass = 'com.animation.sampler.Launcher'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
