plugins {
    id 'application'
}

group = 'com.example'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'com.example.headless.Main'
}

dependencies {
    implementation 'com.badlogicgames.gdx:gdx:1.14.2'
    implementation 'com.badlogicgames.gdx:gdx-backend-headless:1.14.2'
    runtimeOnly 'com.badlogicgames.gdx:gdx-platform:1.14.2:natives-desktop'
}

tasks.named('run', JavaExec) {
    mainClass = application.mainClass
    standardOutput = System.out
    errorOutput = System.err
}
